# -*- mode: python ; coding: utf-8 -*-

# PyInstaller spec file for Sub Extractor GUI
# Build: pyinstaller --clean --noconfirm pyinstaller-gui.spec
# Output: dist/SubExtractor.exe (Windows) or dist/SubExtractor (macOS/Linux)

a = Analysis(
    ['src/sub_extractor/gui/__main__.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'sub_extractor',
        'sub_extractor.cli',
        'sub_extractor.pipeline',
        'sub_extractor.models',
        'sub_extractor.enums',
        'sub_extractor.exceptions',
        'sub_extractor.ffmpeg',
        'sub_extractor.input',
        'sub_extractor.input.base',
        'sub_extractor.input.video_input',
        'sub_extractor.detection',
        'sub_extractor.detection.base',
        'sub_extractor.detection.soft_sub_detector',
        'sub_extractor.detection.external_sub_detector',
        'sub_extractor.detection.hard_sub_detector',
        'sub_extractor.extraction',
        'sub_extractor.extraction.base',
        'sub_extractor.extraction.codec_map',
        'sub_extractor.extraction.ffmpeg_extractor',
        'sub_extractor.extraction.bitmap_extractor',
        'sub_extractor.extraction.ocr_extractor',
        'sub_extractor.processing',
        'sub_extractor.processing.base',
        'sub_extractor.processing.ffmpeg_remuxer',
        'sub_extractor.output',
        'sub_extractor.output.base',
        'sub_extractor.output.file_output',
        'sub_extractor.ocr',
        'sub_extractor.ocr.frame_extractor',
        'sub_extractor.ocr.preprocessor',
        'sub_extractor.ocr.engine',
        'sub_extractor.ocr.deduplicator',
        'sub_extractor.ocr.timestamp',
        'sub_extractor.ocr.formatter',
        'sub_extractor.gui',
        'sub_extractor.gui.main_window',
        'sub_extractor.gui.extract_tab',
        'sub_extractor.gui.info_tab',
        'sub_extractor.gui.check_tab',
        'sub_extractor.gui.pipeline_worker',
        'sub_extractor.gui.models',
        'sub_extractor.gui.widgets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SubExtractor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # Windows: no terminal window (subsystem: windows)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
